# These are supported funding model platforms

github: [arinbalyan] # Replace with your GitHub Sponsors URL
# patreon: # Replace with your Patreon URL
# open_collective: # Replace with your Open Collective URL
# ko_fi: # Replace with your Ko-fi URL
# tidelift: # Replace with your Tidelift URL
# community_bridge: # Replace with your Community Bridge URL
# liberapay: # Replace with your Liberapay URL
# issuehunt: # Replace with your IssueHunt URL
# otechie: # Replace with your Otechie URL
# custom: # Replace with a custom URL (e.g., PayPal, Buy Me a Coffee)
