repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
        args: ["protect", "--staged", "--verbose"]

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint
        args: ["--timeout=5m"]

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt (all files)
        entry: bash -c 'gofmt -w $(find . -name "*.go" -not -path "./vendor/*")'
        language: system
        pass_filenames: false

      - id: go-test
        name: go test (fast check)
        entry: go test ./...
        language: system
        pass_filenames: false
